<!DOCTYPE html>
<html lang="pl">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<title>Patryk Pikor Fotografia</title>
	<meta name="description" content="Fotograf Patryk Pikor">
	<meta name="keywords" content="fotografia, fotograf slubny, zdjecia, patryk, pikor, photography">
	<meta name="author" content="Patryk Pikor">
	<meta http-equiv="X-Ua-Compatible" content="IE=edge">
	
	<link rel="stylesheet" href="main.css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova:400,600&display=swap&subset=latin-ext" rel="stylesheet">
	<link href="css/fontello.css" rel="stylesheet" type="text/css">
	<link href="css/jquery.tabSlideOut.css" rel="stylesheet" type="text/css">
	<!--[if lt IE 9]>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->
	
</head>
<body>
	<header>
	<div class="background-nav-logo">
			<div class="logo">
				<h1> Patryk Pikor Fotografia </h1>
			</div>
		<nav>
				<div class="line-nav menu">
					
					<a href="index.php">Home</a>
					<a href="about-me.php">O mnie</a>
					<a href="#">Zdjęcia ślubne</a>
					<a href="portfolio.php">Portfolio</a>
					<a href="kontakt.php">Kontakt</a>
					<div class="effect"></div>
					
				</div>
	
		</nav>
	</div>
	</header>
	
	<div class="container">
		<main>
			<article>
					<header>
						<div class="container-p">
					
							<h2 class="heading">O początkach mojej podróży z fotografią....</h2>
		
		<p>Zaczęło się niewinne od suwenira, który otrzymałem od mojego starszego brata był to mały kompaktowy aprat marki Samsung, strzał w dziesiątke. Miałem możliwość ukazać cały otaczający mnie świat za pomocą małego pudełka. Nie wiedząc jeszcze w jaki sposób utrwala ujęte przeze mnie kadry zacząłem tworzyć, biegać, poszukiwać. To ciągła podróż, która nadal trwa nieprzerwanie. Miło jest wspominać pierwsze momenty, kiedy to cieszysz się jako małe dziecko z zabawki, o którym mało jeszcze wiesz oraz jakie możliwości ono daje.</p>
		<p>Można powiedzieć, że wyssałem fotografię z mlekiem matki. Tak... Moi rodzice, także się fascynowali tą dziedziną sztuki czysto hobbistycznie. Wsparcie oraz autorytet na samym początku był ogromną zaletą, za co niezmiernie im dziękuje.</p>
									
							</div>
							
					</header>
			
			</article>
		</main>
</div>

			

<footer>
<!--This webfont is generated by http://fontello.com -->
		<div class="socials">
				<div class="socialdivs">
						<div class="fb"><a href="https://www.facebook.com/" target="_blank" class="sociallink"><i class="icon-facebook"></i></a></div>
						<div class="tw"><a href="https://twitter.com/" target="_blank" class="sociallink"><i class="demo-icon icon-twitter"></i></a></div>
						<div class="insta"><a href="https://www.instagram.com/pikor.patryk/" target="_blank" class="sociallink"><i class="demo-icon icon-instagram"></i></a></div>
						<div class="yt"><a href="https://www.youtube.com/" target="_blank" class="sociallink"><i class="demo-icon icon-youtube"></i></a></div>
						<div class="gplus"><a href="https://aboutme.google.com/u/0/?referer=gplus" target="_blank" class="sociallink"><i class="demo-icon icon-gplus"></i></a></div>
					<div style="clear: both;"><i></i></div>
				</div>
		</div>
		
		<div class="info">
		All rights reserved &copy; 2019 Thanks for visit! 
		</div>
		
</footer>

	<script src="js/jquery-3.4.1.min.js"></script>
	<script src="js/jquery.tabSlideOut.js"></script>
	<div id="my-tab"><span class="handle">Instagram</span>Hello World</div>
	
	<script>
		$('#my-tab').tabSlideOut( {
		'tabLocation':'left',
		'action':'hover'
		} );
	</script>
	
	
</body>
</html>
