<!DOCTYPE html>
<html lang="pl">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<title>Patryk Pikor Fotografia</title>
	<meta name="description" content="Fotograf Patryk Pikor">
	<meta name="keywords" content="fotografia, fotograf slubny, zdjecia, patryk, pikor, photography">
	<meta name="author" content="Patryk Pikor">
	<meta http-equiv="X-Ua-Compatible" content="IE=edge">
	
	<link rel="stylesheet" href="main.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova:400,600&display=swap&subset=latin-ext" rel="stylesheet">
	<link href="css/fontello.css" rel="stylesheet" type="text/css">
	<link href="css/jquery.tabSlideOut.css" rel="stylesheet" type="text/css">
	<!--[if lt IE 9]>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->
	
</head>
<body>
	<header>
	<div class="background-nav-logo">
			<div class="logo">
				<h1> Patryk Pikor Fotografia </h1>
			</div>
		<nav>
				<div class="line-nav menu">
					
					<a href="index.php">Home</a>
					<a href="about-me.php">O mnie</a>
					<a href="#">Zdjęcia ślubne</a>
					<a href="portfolio.php">Portfolio</a>
					<a href="kontakt.php">Kontakt</a>
					<div class="effect"></div>
					
				</div>
	
		</nav>
	</div>
	</header>

			<div class="photo-js">
			  <img class="mySlides" src="img/1.jpg">
			  <img class="mySlides" src="img/2.jpg">
			  <img class="mySlides" src="img/4.jpg">
			</div>

<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 5000); // Change image every 5 seconds
}
</script>
<div class="container">
		<main>
			<article>
					<header>
						<div class="container-p">
					
							<h2 class="heading">Fotograf Patryk Pikor i jego życiowa pasja...</h2>
					
					
					
							<p> Zdjęcia, a zwłaszcza fotografie portretowe pozwalają uwiecznić najdrobniejsze grymasy twarzy. To one pozwalają ukazać zwierciadło duszy poprzez głębię i piękno oczu osób fotografowanych. Nie ma znaczenia czy wykonywane są z ukrycia błąkając się po ulicach miasta czy spokojnie pozowane w zaciszu studia fotograficznego. Wszystkie łączy jedno piękno ludzkiej twarzy, ich unikalność i tajemnica wyryta niczym dłutem prez rzeźbiarza. Każda osoba niesie ze sobą historię. Nie zawsze jest widoczna, jedynie bliższe poznanie za pomocą aparatu pozwala ukazać to co jest dyskretne i schowane. </p>
						
							<p> Wybór odpowiedniego fotografa nie jest łatwym zadaniem. Na rynku mamy mnogość osób, które się tą sztuką parają, lecz trzeba wybrać. Ale kogo? </p>
							
							<div id="img-home-inscription"><img src="img/16.jpg"></div>

							<p> Sprawdź portfolio fotografa, to ono w pierwszej fazie poznania pozwoli określić czy dana osoba jest godna uwiecznienia nas na kliszy. Jeśli posiada własny unikalny styl oraz widać gołym okiem, iż jest to jego pasja już wiesz kogo wybrać. Warto także sprawdzić opinie o danym fotografie. W social mediach na fanpagu lub na stonie, a także spróbować nawiązać kontakt z poprzednimi klientami. Mogą przekazać cenne informacje, które pozwolą zweryfikować umiejętności. Cena za usługę nie zawsze powinna być wyznacznikiem jakości, o czym należy pamiętać. Czasem mamy doczynienia dopiero co wkraczającymi w świat fotografii artystami, którzy swą niższą ceną, a niżeli rynkową starają się zachęcić innych do wypróbowania ich warsztatu. Warto spróbować lub choćby zaintaresować się nimi.
							</p>
							<h4>Zapraszam Ciebie do zapoznania się z moim portfolio na stronie, bądź do kontaktu ze mną :) </h4>
								
							</div>
							
					</header>
			
			</article>
		</main>
</div>
<footer>
<!--This webfont is generated by http://fontello.com open source project.-->
		<div class="socials">
				<div class="socialdivs">
						<div class="fb"><a href="https://www.facebook.com/" target="_blank" class="sociallink"><i class="icon-facebook"></i></a></div>
						<div class="tw"><a href="https://twitter.com/" target="_blank" class="sociallink"><i class="demo-icon icon-twitter"></i></a></div>
						<div class="insta"><a href="https://www.instagram.com/pikor.patryk/" target="_blank" class="sociallink"><i class="demo-icon icon-instagram"></i></a></div>
						<div class="yt"><a href="https://www.youtube.com/" target="_blank" class="sociallink"><i class="demo-icon icon-youtube"></i></a></div>
						<div class="gplus"><a href="https://aboutme.google.com/u/0/?referer=gplus" target="_blank" class="sociallink"><i class="demo-icon icon-gplus"></i></a></div>
					<div style="clear: both;"><i></i></div>
				</div>
		</div>
		
		<div class="info">
		All rights reserved &copy; 2019 Thanks for visit! 
		</div>
		
</footer>

	<script src="js/jquery-3.4.1.min.js"></script>
	<script src="js/jquery.tabSlideOut.js"></script>
	<div id="my-tab"><span class="handle">Instagram</span>Hello World</div>
	
	<script>
		$('#my-tab').tabSlideOut( {
		'tabLocation':'left',
		'action':'hover'
		} );
	</script>
	
	
</body>
</html>
