<?php
session_start();
?>

<!DOCTYPE html>
<html lang="pl">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<title>Patryk Pikor Fotografia</title>
	<meta name="description" content="Fotograf Patryk Pikor">
	<meta name="keywords" content="fotografia, fotograf slubny, zdjecia, patryk, pikor, photography">
	<meta name="author" content="Patryk Pikor">
	<meta http-equiv="X-Ua-Compatible" content="IE=edge">
	
	<link rel="stylesheet" href="main.css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova:400,600&display=swap&subset=latin-ext" rel="stylesheet">
	<link href="css/fontello.css" rel="stylesheet" type="text/css">
	<link href="css/jquery.tabSlideOut.css" rel="stylesheet" type="text/css">
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<!--[if lt IE 9]>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->
	
</head>
<body>
	<header>
	<div class="background-nav-logo">
			<div class="logo">
				<h1> Patryk Pikor Fotografia </h1>
			</div>
		<nav>
				<div class="line-nav menu">
					
					<a href="index.php">Home</a>
					<a href="about-me.php">O mnie</a>
					<a href="#">Zdjęcia ślubne</a>
					<a href="portfolio.php">Portfolio</a>
					<a href="kontakt.php">Kontakt</a>
					<div class="effect"></div>
					
				</div>
	
		</nav>
	</div>
	</header>
		

			<div class="container-kontakt">
			
					<div class="east-side">
				<header>
					<h1>Formularz kontaktowy</h1>
				</header>
		<main>
			<article>
					<form action="save.php" method="post">
						
						<!--<div class="row">
							
							<label> <input type="txt"  placeholder=" Imię i nazwisko" name="name"/></div>
						
						-->
						<div class="row">
						
							<label><input type="email" placeholder=" Adres e-mail" name="email"
							<?= isset($_SESSION['given_email']) ? 'value="'.$_SESSION['given_email'].'"' : ''//jeśli adres jest niepoprawny to zostawiamy go w polu input, zeby nie było puste?>
                        <?= isset($_SESSION['ok_email']) ? 'value="'.$_SESSION['ok_email'].'"' : ''; unset($_SESSION['ok_email'])//jeśli adres jest niepoprawny to zostawiamy go w polu input, zeby nie było puste?>
							/></div>
						<!--
						<div class="row">
						
							<label><input type="tel" placeholder=" Numer Telefonu" name="phone"/></div>
						
						-->
						<div class="row">
							<input type="submit" value="Wyślij">
							
					</div>
						
						<div class="row">
							<?php
                    ///////////

                    if(isset($_SESSION['existing_email']))
                    {
                        echo '<p>Taki email już istnieje w bazie!</p>';
                        unset($_SESSION['existing_email']);
                    }


                    /////////////
                    if(isset($_SESSION['given_email']))
                    {
                        echo '<p>To nie jest poprawny email!</p>';
                        unset($_SESSION['given_email']);//po wyswietlaniu komunikatu usuwamy zmienna z blednym adresem
                    }
                    ?>


                    <div class="g-recaptcha" data-sitekey="6LflLtgUAAAAAF4MhSGn8yp8r70QN0Y08r1CN56J"></div>

                    <?php
                    if(isset($_SESSION['no_captcha']))
                    {
                        echo $_SESSION['no_captcha'];
                        unset($_SESSION['no_captcha']);//po wyswietlaniu komunikatu usuwamy zmienna z nieistniejaceym adresem
                    }
                    ?>

						</div>
					</div>
					
					</form>
					
				</article>
			</main>
			
			
				</div> <!-- div class east side-->
					
					<div class="west-side">
					
					<p>Patryk Pikor</p>
					<p>E-mail: patryk.pikor02@gmail.com</p>
					<p>Tel. +48 508 816 279</p>
					<p id="pad-p">Social Media:</p>
					<a href="#"><p>Instagram</p></a>
					<a href="#"><p>Facebook</p></a>
					<a href="#"><p>Google+</p></a>
					<a href="#"><p>Twitter</p></a>
					<a href="#"><p>YouTube</p></a>
					
					
					</div>
				
				<div style="clear: both;"></div>
				
			</div>
<footer>
<!--This webfont is generated by http://fontello.com open source project.-->
		<div class="socials">
				<div class="socialdivs">
						<div class="fb"><a href="https://www.facebook.com/" target="_blank" class="sociallink"><i class="icon-facebook"></i></a></div>
						<div class="tw"><a href="https://twitter.com/" target="_blank" class="sociallink"><i class="demo-icon icon-twitter"></i></a></div>
						<div class="insta"><a href="https://www.instagram.com/pikor.patryk/" target="_blank" class="sociallink"><i class="demo-icon icon-instagram"></i></a></div>
						<div class="yt"><a href="https://www.youtube.com/" target="_blank" class="sociallink"><i class="demo-icon icon-youtube"></i></a></div>
						<div class="gplus"><a href="https://aboutme.google.com/u/0/?referer=gplus" target="_blank" class="sociallink"><i class="demo-icon icon-gplus"></i></a></div>
					<div style="clear: both;"><i></i></div>
				</div>
		</div>
		
		<div class="info">
		All rights reserved &copy; 2019 Thanks for visit! 
		</div>
		
</footer>

	<script src="js/jquery-3.4.1.min.js"></script>
	<script src="js/jquery.tabSlideOut.js"></script>
	<div id="my-tab"><span class="handle">Instagram</span>Hello World</div>
	
	<script>
		$('#my-tab').tabSlideOut( {
		'tabLocation':'left',
		'action':'hover'
		} );
	</script>
	
	
</body>
</html>
